from langchain_core.prompts import ChatPromptTemplate

########## Generator Prompt ##########
generator_system_template = """
### ROLE
You are an expert Data Steward specializing in Enterprise Data Governance. Your task is to populate a Business Glossary with high-accuracy metadata and to return the **COMPLETE** Business Glossary table!
"""

generator_human_template = """
### INPUT DATA ###
1. **TARGET_TABLE**: Contains current metadata. Fields marked `<agent>` must be populated. Fields with existing text are "Source of Truth" and must be used as guidance/context for the missing fields.
   {full_table_context}

2. **COMPANY_CONTEXT (RAG)**: A JSON collection of 'hits' containing 'text' and 'source'. Use this as your primary evidence.
   {rag_company_context}
   
3. Each column field is clearly defined in the Pydantic schema supplied to you in the Structured Output called **TemplateOutput**.


### EXTRACTION RULES & LOGIC ###
For every field marked `<agent>`, apply the following logic:

* **Source Priority**:
    1. Primary: Use **COMPANY_CONTEXT (RAG)**.
    2. Secondary: If RAG is silent, infer meaning from the **TARGET_TABLE** (existing descriptions of related columns or sample values).
    3. Tertiary: Use your internal expertise to provide the most likely business definition.


### CONSTRAINTS ###
- Your goal is to fill the table as much as possible. Do not leave fields blank if a reasonable business inference can be made from the column name or samples. None of the fields can be left blank!
- DO NOT modify any values in the table that are NOT marked with `<agent>`.
- Maintain professional, neutral language.


### RECONSTRUCTION RULE
- For fields that were **already filled** in the input: Copy them exactly into your response.
- For fields marked `<agent>`: Replace the tag with your generated metadata.
- The number of objects in your output `result` list must exactly match the number of columns in the input. In other words, you need to fill all the columns defined in the **ColumnDefOutput**
- The length of the list defined in the **TemplateOutput** must match exactly the number of rows of the **TARGET_TABLE** which where provided to you as the input.

{critic_feedback}
"""

GENERATOR_PROMPT = ChatPromptTemplate.from_messages([
    ("system", generator_system_template),
    ("human", generator_human_template)
])


########## Validator Prompt ##########
validator_system_template = """
### ROLE
You are a Senior Data Governance Auditor. Your task is to validate the accuracy and logic of a Business Glossary.
"""

validator_human_template = """
### CONTEXT
PRIMARY EVIDENCE (RAG): {rag_company_context}
SECONDARY CONTEXT (Full Table/Samples): {full_table_context}

### WORK TO REVIEW
Data Table:
{current_work}
Table Summary
{current_work_table_summary}

### VALIDATION RULES
1. **Check RAG Consistency**: If Source used is a document name, verify the proposed Descriptions matches the facts in the PRIMARY EVIDENCE and whether it make sense.
2. **Check Inference Logic**: If Source used is 'Agent Logic', verify if the description is a reasonable "smart guess" based on the column name and table context.
   *Example: If column is 'strt' and contains 'Washington St', the definition should be about Address/Location.*
3. **Quality Check**:
   - Ensure no technical jargon (like 'VARCHAR' or 'NULL') is provided inside the description.
   - Ensure the Generator provided a source. If it says "Agent Knowledge" when the info was clearly in the RAG, flag this.
4. **Table Summary Check**: 
   - Make your own evaluation if the Table Summary generated by the model makes sense given the context and the definitions provided in the rows. The summary should be concise, ideally not more than 2-3 sentences and explains what is the main purpose of this table.
   
### OUTPUT
1. Evaluate if the definitions are sensible. If any description is misleading, or if the agent ignored the provided RAG context, set is_valid = False and provide specific feedback for those columns.
2. It is crucial that number of rows matches the expected number of rows. In this case {mismatch_message}.
3. Make sure none of the rows were left empty. All have to be filled in. If any row is empty, set is_valid = False and state "Empty definition for row Y column X".
"""

VALIDATOR_PROMPT = ChatPromptTemplate.from_messages([
    ("system", validator_system_template),
    ("human", validator_human_template)
])